#!/bin/sh

# cd into test-cases directory
cd `echo "$0" | sed 's/run-all-unit-tests/test-cases/'`

all_archs="ppc ppc64 i386 x86_64"

for arch in $all_archs
do
	echo ""
	echo " * * * Running all unit tests for architecture $arch * * *"

	# build architecture
	../bin/make-recursive.pl ARCH=$arch VALID_ARCHS="$all_archs" | ../bin/result-filter.pl

	# clean up so svn is happy
	../bin/make-recursive.pl ARCH=$arch clean > /dev/null

	echo ""
done



